import "@repo/ui/styles.css";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import type { Metadata } from "next";
import NavBarLanding from "../components/pages/Landing/NavBarLanding";
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NavBarLanding />
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
